/// @function level_select_get_next_room
/// @summary Get the next configured campaign room.
/// @param {string|asset.GMRoom} _current_room Current room or level identifier
/// @returns {asset.GMRoom} Next room asset
function level_select_get_next_room(_current_room) {
	var _next_level = level_select_get_next_level(_current_room);
	
	if (!is_undefined(_next_level)) {
		return _next_level.level_room;
	}
	
	// Fallback to test level if not found
	return r_game_level_0;
}

/// @function level_select_build_transition
/// @summary Resolve the next campaign transition and apply completion/unlock state.
/// @param {asset.GMRoom} _current_room Current room
/// @returns {struct|undefined} Transition data or undefined if the room is not registered
function level_select_build_transition(_current_room) {
	var _current_data = level_select_get_data(_current_room);
	if (is_undefined(_current_data)) {
		return undefined;
	}
	
	var _next_level = level_select_get_next_level(_current_room);
	var _next_room = !is_undefined(_next_level) ? _next_level.level_room : r_game_level_0;
	var _target_room = _next_room;
	var _route_via_presence = false;
	
	if (
		_current_data.transition_style == LEVEL_SELECT_TRANSITION_VIA_PRESENCE_HUB
		&& _current_data.level_room != r_game_level_presence
	) {
		_route_via_presence = true;
		_target_room = r_game_level_presence;
	}
	
	level_select_complete(_current_room);
	o_director.next_level = _next_room;
	
	return {
		current_data : _current_data,
		next_level : _next_level,
		target_room : _target_room,
		route_via_presence : _route_via_presence,
	};
}

/// @function level_select_apply_transition
/// @summary Execute a campaign transition generated by level_select_build_transition.
/// @param {struct} _transition Transition data
/// @param {bool} _safe_transition Whether to apply play-state safeguards before switching rooms
/// @returns {bool} True if the transition was applied
function level_select_apply_transition(_transition, _safe_transition) {
	if (is_undefined(_transition)) {
		return false;
	}
	
	if (
		_safe_transition
		|| _transition.current_data.transition_style == LEVEL_SELECT_TRANSITION_DIRECT
	) {
		o_director.level_transitioning = true;
		global.game_state = GameState.play;
		global.game_state_target = noone;
	}
	
	room_goto(_transition.target_room);
	return true;
}
